source 'https://rubygems.org'

gem 'json', '~> 1.8.0'
gem 'rake'
gem 'thin'
gem 'sinatra'
gem 'sinatra-flash'
gem 'activerecord', '~> 4.1.10'
gem 'sinatra-activerecord'
gem 'sinatra-authentication', :git => "https://github.com/zquestz/sinatra-authentication", :branch => 'master'
gem 'sinatra-i18n'
gem 'sqlite3', '~> 1.3.13'
gem 'mysql2', '~> 0.3.0'
gem 'dalli', '~> 2.7.9'
gem 'rack-fiber_pool'
gem 'em-resolv-replace'
gem 'mime-types'
gem 'haml'
gem 'sass'
gem 'rack-test'
gem 'minitest'
gem 'simplecov', '>= 0.4.0', :require => false, :group => :test
gem 'em-synchrony', git: 'https://github.com/igrigorik/em-synchrony'
gem 'em-http-request'
gem 'tux'
