source 'https://rubygems.org'

gem 'rake'
gem 'thin'
gem 'sinatra'
gem 'activerecord', '4.1.10'
gem 'sinatra-activerecord'
gem 'sinatra-i18n'
gem 'sqlite3'
gem 'mysql2'
gem 'dalli'
gem 'rack-fiber_pool'
gem 'em-resolv-replace'
gem 'mime-types'
gem 'haml'
gem 'less'
gem 'rack-test'
gem 'minitest'
gem 'simplecov', '>= 0.4.0', :require => false, :group => :test
gem 'em-synchrony', :git => 'git://github.com/igrigorik/em-synchrony.git'
gem 'em-http-request'
gem 'tux'
gem 'therubyracer'
