require 'fiber'
require 'rack/fiber_pool'
require 'rack/session/cookie'
require 'sinatra'
require 'sinatra/flash'
require 'tilt/haml'
require 'tilt/sass'
require 'sinatra/activerecord'
require 'sinatra/i18n'
require 'resolv'
require 'em-resolv-replace' unless test?
require 'mime/types'
require 'dalli'
require 'em-synchrony/em-http'
require 'em-synchrony/activerecord'
require 'sinatra-authentication'
